11/11/2014 14:47:46 WARNING nemoa.workspace.base.get -> could not get configuration: system with name 'rbm' is not known.
11/11/2014 14:47:46 ERROR nemoa.system.imports.load -> could not import system: current workspace 'tutorial' does not contain a system 'rbm'.
11/11/2014 14:47:46 ERROR File "/usr/bin/ipython", line 6, in <module>->   start_ipython()
11/11/2014 14:47:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 118, in start_ipython->   return launch_new_instance(argv=argv, **kwargs)
11/11/2014 14:47:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 546, in launch_instance->   app.start()
11/11/2014 14:47:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 362, in start->   self.shell.mainloop()
11/11/2014 14:47:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 436, in mainloop->   self.interact(display_banner=display_banner)
11/11/2014 14:47:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 555, in interact->   self.run_cell(source_raw, store_history=True)
11/11/2014 14:47:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2660, in run_cell->   interactivity=interactivity, compiler=compiler)
11/11/2014 14:47:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2764, in run_ast_nodes->   if self.run_code(code):
11/11/2014 14:47:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2820, in run_code->   exec code_obj in self.user_global_ns, self.user_ns
11/11/2014 14:47:46 ERROR File "<ipython-input-5-249ebea9b180>", line 1, in <module>->   model = nemoa.model.create(dataset = 'noise', network = nemoa.network.create('multilayer', shape = []), system = 'rbm')
11/11/2014 14:47:46 ERROR File "./package/nemoa/model/__init__.py", line 18, in create->   return new(**nemoa.model.builder.build(*args, **kwargs))
11/11/2014 14:47:46 ERROR File "./package/nemoa/model/builder/__init__.py", line 38, in build->   model = nemoa.model.builder.base.build(type, *args, **kwargs)
11/11/2014 14:47:46 ERROR File "./package/nemoa/model/builder/base.py", line 21, in build->   if type == 'model': return Model(**kwargs).build()
11/11/2014 14:47:46 ERROR File "./package/nemoa/model/builder/base.py", line 68, in build->   = nemoa.system.load(self.settings['system'])
11/11/2014 14:47:46 ERROR File "./package/nemoa/system/__init__.py", line 18, in load->   return nemoa.system.imports.load(*args, **kwargs)
11/11/2014 14:47:46 ERROR File "./package/nemoa/system/imports/__init__.py", line 63, in load->   '%s'.""" % (current_workspace, path))
11/11/2014 14:47:46 ERROR File "./package/nemoa/common/log.py", line 164, in log->   for line in traceback.format_stack():
11/11/2014 15:57:00 WARNING nemoa.workspace.base.get -> could not get configuration: model with name 'sinus-ann(4,2)-dbn' is not known.
11/11/2014 15:57:00 ERROR nemoa.model.imports.load -> could not import model: current workspace 'tutorial' does not contain a model 'sinus-ann(4,2)-dbn'.
11/11/2014 15:57:00 ERROR File "/usr/bin/ipython", line 6, in <module>->   start_ipython()
11/11/2014 15:57:00 ERROR File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 118, in start_ipython->   return launch_new_instance(argv=argv, **kwargs)
11/11/2014 15:57:00 ERROR File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 546, in launch_instance->   app.start()
11/11/2014 15:57:00 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 362, in start->   self.shell.mainloop()
11/11/2014 15:57:00 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 436, in mainloop->   self.interact(display_banner=display_banner)
11/11/2014 15:57:00 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 555, in interact->   self.run_cell(source_raw, store_history=True)
11/11/2014 15:57:00 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2660, in run_cell->   interactivity=interactivity, compiler=compiler)
11/11/2014 15:57:00 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2764, in run_ast_nodes->   if self.run_code(code):
11/11/2014 15:57:00 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2820, in run_code->   exec code_obj in self.user_global_ns, self.user_ns
11/11/2014 15:57:00 ERROR File "<ipython-input-10-8a5406a293f8>", line 1, in <module>->   model = nemoa.model.open('sinus-ann(4,2)-dbn')
11/11/2014 15:57:00 ERROR File "./package/nemoa/model/__init__.py", line 30, in open->   return new(**load(*args, **kwargs))
11/11/2014 15:57:00 ERROR File "./package/nemoa/model/__init__.py", line 22, in load->   return nemoa.model.imports.load(*args, **kwargs)
11/11/2014 15:57:00 ERROR File "./package/nemoa/model/imports/__init__.py", line 57, in load->   '%s'.""" % (current_workspace, path))
11/11/2014 15:57:00 ERROR File "./package/nemoa/common/log.py", line 164, in log->   for line in traceback.format_stack():
